name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.8.0
      with:
        # Directory to install Qt
        dir: # optional
        # Version of Qt to install
        version:  5.12.9 # optional, default is 5.12.9
        # Host platform
        host: linux
        # Target platform for build
        target: desktop # optional, default is desktop
        # Architecture for Windows/Android
        arch: # optional
        # Whether or not to install Qt dependencies on Linux
        install-deps: # optional, default is true
        # Additional Qt modules to install
        modules: widgets charts # optional
        # Force a Qt mirror in case the default is not working
        mirror: # optional
        # Whether or not to actually download Qt
        cached: # optional, default is false
        # Version of aqtinstall to use in case of issues
        aqtversion: # optional, default is ==0.9.4
        # Version of py7zr to use in case of issues
        py7zrversion: # optional, default is ==0.9.1
        # Any extra arguments to append to the back
        extra: # optional
    - name: Build CMake
      uses: ashutoshvarma/action-cmake-build@v1
      with:
        # Build directory where build files will be generated
        build-dir: build # ${{ runner.workspace }}/build
        # CMake build type (Release, Debug, MinSizeRel, RelWithDebInfo)
        build-type: Release
        # C Compiler for toolchain
        cc: gcc
        # C++ Compiler for toolchain
        cxx: g++
        # CMake build target
        target: all # optional
        # Number of concurrent jobs for build and test
        parallel: 4 # optional, default is 4
        # Run CTest or not
        run-test: false # optional, default is false
        # Run 'cmake --install' or not
        install-build: false # optional, default is false
        # Update git submodules
        submodule-update: false # optional, default is false
        # Misc Options to pass to CMake while configuring project
        configure-options: # optional
        # Misc Options to pass to CMake while building project using cmake --build
        build-options: # optional
        # Misc Options to pass to CMake while installing project using cmake --install
        install-options: # optional
        # Misc Options to pass to CTest
        ctest-options: # optional

